# Generated by Django 4.1.7 on 2023-05-29 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year_founded', models.IntegerField()),
                ('coverage_EU', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Balloon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_passengers', models.IntegerField()),
                ('type', models.CharField(choices=[('Hot Air Balloon', 'Hot Air Balloon'), ('Helium Balloon', 'Helium Balloon'), ('Hydrogen Balloon', 'Hydrogen Balloon')], max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('year_of_birth', models.IntegerField()),
                ('total_hours', models.IntegerField()),
                ('role', models.CharField(choices=[('Pilot', 'Pilot'), ('Co-pilot', 'Co-pilot'), ('Navigator', 'Navigator'), ('Flight Attendant', 'Flight Attendant')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='flights/')),
                ('takeoff_airport', models.CharField(max_length=255)),
                ('landing_airport', models.CharField(max_length=255)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hot_air_balloon.airline')),
                ('balloon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hot_air_balloon.balloon')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hot_air_balloon.pilot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AirlinePilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hot_air_balloon.airline')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hot_air_balloon.pilot')),
            ],
        ),
    ]
